Update update-configs.yml

diff --git a/.github/workflows/update-configs.yml b/.github/workflows/update-configs.yml
--- a/.github/workflows/update-configs.yml
+++ b/.github/workflows/update-configs.yml
@@ -6,15 +6,14 @@ on:
     branches:
       - main
   schedule:
-    # Run every 10 minutes
-    - cron: "*/10 * * * *"
+    - cron: "*/15 * * * *"
 
 jobs:
   update-configs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -25,7 +24,6 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-
       - name: Update V2Ray configs
         run: python src/update_v2ray.py
 
@@ -38,14 +36,45 @@ jobs:
       - name: Update contributors
         run: python src/update_contributors.py
 
-      - name: Commit and push changes
-        uses: stefanzweifel/git-auto-commit-action@v4
+      - name: Commit Files
+        run: |
+          git config --local user.email "ghanbarimatin6@gmail.com"
+          git config --local user.name "Matin Ghanbari"
+          git add subscriptions
+          git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
+      
+      - name: Push Changes
+        uses: ad-m/github-push-action@v0.6.0
         with:
-          commit_message: "🔄 Auto-update configs (10 min interval)"
+          github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: main
-          file_pattern: "subscriptions/* public/assets/data/*"
-          commit_user_name: GitHub Actions
-          commit_user_email: actions@github.com
-          commit_author: GitHub Actions <actions@github.com>
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
+      # - name: Clean Up Files
+      #   run: |
+      #     git checkout --orphan latest_branch
+      #     git rm -r -f __pycache__ || true
+      #     git config --local user.email "ghanbarimatin6@gmail.com"
+      #     git config --local user.name "Matin Ghanbari"
+      #     git add subscriptions
+      #     git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
+      #     git branch -D main
+      #     git branch -m main
+      #     git push -f origin main
+
+      # - name: Push Changes
+      #   uses: ad-m/github-push-action@v0.6.0
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     branch: main
+          
+      # - name: Commit and push changes
+      #   uses: stefanzweifel/git-auto-commit-action@v4
+      #   with:
+      #     commit_message: "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
+      #     commit_user_name: GitHub Actions
+      #     commit_user_email: actions@github.com
+      #     commit_author: GitHub Actions <actions@github.com>
+      #     file_pattern: "subscriptions/* public/assets/data/*"
+      #     branch: main
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
